### PR TITLE
Clever code distracts from actual example.

### PR DESCRIPTION
**Pull request by ccoenen**
Example code should be as clear as possible and focus on the task being shown. In my opinion there is really no point in using the reduce-construct.

### CODE REVIEW

**Comment by callmecavs** [comment]
@ccoenen imo the `reduce` function doesn't qualify as "overly-clever" (i prefer to keep selecting elements as DRY as possible) - but I do see your point in that it doesn't help illustrate the capabilities of the library at all.

happy to merge this in, but could you do me a favor and remove the `;`? `gotem` follows [`standard`](https://github.com/feross/standard) style, and for consistencies sake the README should to

**Comment by callmecavs** [comment]
@ccoenen nvm, I'll fix it when I bump the version number. thanks dude!

**Comment by ccoenen** [comment]
thanks for the heads up, I'll be more careful with code style next time.

**Comment by callmecavs** [comment]
just the README so its not a big deal haha, thanks again

**Pull request merged**
